config/routes.rb
Rails.application.routes.draw do
  resources :home, only: [:index]

  get 'home/login'

  post 'users/login'

  resources :users do
    post 'logout'
  end
  root 'home#login'

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :tracks
end

app/models/track.rb
class Track < ActiveRecord::Base
  has_and_belongs_to_many :playlists
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :playlists

  has_attached_file :avatar, :styles => { :medium => "200x200>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def password
    @password ||= BCrypt::Password.new(password_hash) #if password_hash.present?
  end

  def password=(new_password)
    @password = BCrypt::Password.create(new_password)
    self.password_hash = @password
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def login

  end

  def index
    @user = User.new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def login
    @user = User.find_by(email: params["user"][:email])
    if @user && @user.password == params["user"][:password_hash]
      signin(@user)
      redirect_to @user
    else
      redirect_to '/'
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      signin(@user)
      redirect_to @user
    end
  end

  def logout
    logout!
    redirect_to '/'
  end

  def show
    @user = User.find(params[:id])
    @playlists = Playlist.where(user_id: @user.id)
    @playlist = Playlist.new
  end


private
  def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :avatar)
  end

  def signin(user)
    session[:user_id] = user.id
  end

  def logout!
    session[:user_id] = nil
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def logged_in?
    current_user.present?
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.where(id: session[:user_id]).first
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper



  def logged_in?
    current_user.present?
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.where(id: session[:user_id]).first
    end
  end

end

app/views/home/index.html.erb
  <div id="head-wrapper">

    <div id="user-container">
      <div id="logo-container">
        <h2 class="heading" id="logo">Spoti-Search</h2>
      </div>

      <div id = "search-container">
            <%= form_for(:track, :html => {:id => "search-form"}) do |f| %>
            <%= f.text_field :title, :class => "large-textbox", :placeholder => "Artist Name"%>
            <%= f.submit "Search", :class => "large-textbox-submit" %>
            <%end%>
      </div>

    </div>
  </div>

<div id="overall-container">

  <div id= "search-results-container">
    <div id="media-wrapper">
      <%= render partial: '/playlists/artist_template' %>
      <%= render partial: '/playlists/related_artists_template' %>
    </div>
      <%= render partial: '/playlists/album_template' %>

  </div>

app/views/home/login.html.erb
<html>
  <head>

  </head>

  <body>
    <div class="container" id="home-container">
      <div id="main-logo">
        Spoti-Search
      </div>
      <div id="login">
        <a id="login-div" href= "#">
          <div id="login-button" class="btn btn-primary">
            Log in with Spotify
          </div>
        </a>
      </div>
    </div>

    <script>

        var stateKey = 'spotify_auth_state';

        function getHashParams() {
          var hashParams = {};
          var e, r = /([^&;=]+)=?([^&;]*)/g,
              q = window.location.hash.substring(1);
          while ( e = r.exec(q)) {
             hashParams[e[1]] = decodeURIComponent(e[2]);
          }
          return hashParams;
        }


        function generateRandomString(length) {
          var text = '';
          var possible = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
          for (var i = 0; i < length; i++) {
            text += possible.charAt(Math.floor(Math.random() * possible.length));
          }
          return text;
        };

        var params = getHashParams();
        var access_token = params.access_token,
            state = params.state,
            storedState = localStorage.getItem(stateKey);
        if (access_token && (state == null || state !== storedState)) {
          alert('There was an error during the authentication');
        } else {
          localStorage.removeItem(stateKey);


          document.getElementById('login-button').addEventListener('click', function() {
            var client_id = '9f2e9952d5a649bf846c1f2963f60fc0'; // Your client id
            var redirect_uri = 'http://spoti-search.herokuapp.com/home'; // Your redirect uri
            var state = generateRandomString(16);
            localStorage.setItem(stateKey, state);
            var scope = 'user-read-private user-read-email';
            var url = 'https://accounts.spotify.com/authorize';
            url += '?response_type=token';
            url += '&client_id=' + encodeURIComponent(client_id);
            url += '&scope=' + encodeURIComponent(scope);
            url += '&redirect_uri=' + encodeURIComponent(redirect_uri);
            url += '&state=' + encodeURIComponent(state);
            window.location = url;
          }, false);
        };
    </script>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Spoti-Search</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Bevan' rel='stylesheet' type='text/css'>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/playlists/_album_template.html.erb
<script id="album-stuff" type="text/x-handlebars-template">
  {{#each albums}}
  <div id = {{id}} class="spotify-player">
        <h4 class= "album-title">{{name}}</h4>
        <iframe src="https://embed.spotify.com/?uri=spotify:album:{{id}}" width="275" height="380" frameborder="0" allowtransparency="true"></iframe>
  </div>
  {{/each}}
</script>

app/views/playlists/_artist_template.html.erb
<script id="artist-stuff" type="text/x-handlebars-template">
  <div id = {{id}} class="artist-div">
    <div class = "artist-info" id="artist-info-{{id}}">
    <h1 class="heading" id="artist-name"> {{name}} </h1>
    <img src= {{images.1.url}} class="artist-photo">
    </div>
    <div id = "artist-{{id}}-albums" class="artist-albums">
    </div>
  </div>
</script>

app/views/playlists/_index.html.erb
<li> <%= item.name %> </li>

<script id="playlists-template" type="text/x-handlebars-template">
  <li> {{name}} </li>
</script>

app/views/playlists/_new_playlist.html.erb
<%= form_for [@user, @playlist], {:id => "new-playlist"} do |f| %>
<%= f.hidden_field :user_id, :value => @user.id%>
<%= f.text_field :name, :class => "large-textbox" %>
<%= f.submit "Create Playlist", :class => "large-textbox-submit" %>

<%end%>

app/views/playlists/_related_artists_template.html.erb
<script id="related-artists" type="text/x-handlebars-template">
<div class= "related-artists-box">
  <h3 class="heading"> Related Artists </h3>
  {{#each artists}}
    <a href="#">
    <img src= {{images.1.url}} title= "{{name}}" data-artist-id= {{id}} class="related-artist-avatar">
    </a>
  {{/each}}
</div>
</script>

app/views/playlists/_tracks_template.html.erb
<script id="tracks-stuff" type="text/x-handlebars-template">
  <ul>
    {{#each tracks}}
      <li id= {{id}}> {{track_number}}. {{name}} </li>
    {{/each}}
  </ul>
</script>

app/views/users/_login.html.erb
<%= form_for(:user,  url: users_login_path, :html => {:id => "sign-in"}) do |f| %>
  <div>
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, :placeholder => "Email" %>
  </div>

  <br>

  <div>
    <%= f.label :password %><br />
    <%= f.password_field :password_hash, autocomplete: "off", :placeholder => "Password" %>
  </div>

 <br>

  <div>
    <%= f.submit "Log in" %>
  </div>

  <%= link_to "Need to sign up?" %>
<% end %>

app/views/users/_sign_up.html.erb
<%= form_for(:user, url: users_path, :html => {:id => "sign-up"}) do |f| %>
  <div>
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name, autofocus: true, :placeholder => "First Name" %>
  </div>


  <div>
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name, autofocus: true, :placeholder => "Last Name" %>
  </div>


  <div>
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, :placeholder => "Email" %>
  </div>


  <div>
    <%= f.label :password %><br />
    <%= f.password_field :password, autocomplete: "off", :placeholder => "Password" %>
  </div>

  <div>
    <%= f.label :avatar %><br />
    <%= f.file_field :avatar %>
  </div>

 <br>

  <div>
    <%= f.submit "Sign Up" %>
  </div>

  <%= link_to "Already have an account?" %>
<% end %>

app/views/users/show.html.erb
  <div id="head-wrapper">
    <div id="user-container">

      <div id="logo-container">
        <h3>Spoti-Search</h3>
      </div>

      <div id = "search-container">
            <%= form_for(:track, :html => {:id => "search-form"}) do |f| %>
            <%= f.text_field :title, :class => "large-textbox", :placeholder => "Artist Name"%>
            <%= f.submit "Search", :class => "large-textbox-submit" %>
            <%end%>
      </div>

      <div id="avatar-container">
        <%= image_tag(@user.avatar.url(:medium), :class => "avatar") %>
         <%if current_user%>
            <%= link_to "logout", user_logout_path(@user), method: :post %>
          <%end%>
      </div>


    </div>
  </div>

<div id="overall-container">

  <div id= "search-results-container">
    <div id="media-wrapper">
      <%= render partial: '/playlists/artist_template' %>
      <%= render partial: '/playlists/related_artists_template' %>
    </div>
      <%= render partial: '/playlists/album_template' %>

  </div>





</div>